version: '3.9'

services:
  web_django:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: "web_app_account"
    env_file:
      - ../.env
    volumes:
      - ../:/django_account
    command:
      "python src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database_app
    ports:
      - "8001:8000"
    networks:
      - custom

  database_app:
    image: postgres:latest
    restart: always
    container_name: "database_account"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5481:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge

volumes:
  postgres-data:
