# Generated by Django 5.1 on 2024-08-09 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Название")),
                ("location", models.CharField(max_length=255, verbose_name="Место хранения")),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
                "db_table": "stock",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Название")),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="Количество")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="equipments", to="inventory.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудования",
                "verbose_name_plural": "Оборудовании",
                "db_table": "equipment",
            },
        ),
    ]
