# Generated by Django 5.1 on 2024-08-09 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="equipments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="equipments", to="inventory.stock"
            ),
        ),
    ]
